/* 닉네임 변경 액션 */
export const CHANGE_NICKNAME_REQUEST = "CHANGE_NICKNAME_REQUEST";
export const CHANGE_NICKNAME_SUCCESS = "CHANGE_NICKNAME_SUCCESS";
export const CHANGE_NICKNAME_FAILURE = "CHANGE_NICKNAME_FAILURE";

export const LOAD_MYPOSTS_REQUEST = "LOAD_MYPOSTS_REQUEST";
export const LOAD_MYPOSTS_SUCCESS = "LOAD_MYPOSTS_SUCCESS";
export const LOAD_MYPOSTS_FAILURE = "LOAD_MYPOSTS_FAILURE";

export const LOAD_MYCOMMENTS_REQUEST = "LOAD_MYCOMMENTS_REQUEST";
export const LOAD_MYCOMMENTS_SUCCESS = "LOAD_MYCOMMENTS_SUCCESS";
export const LOAD_MYCOMMENTS_FAILURE = "LOAD_MYCOMMENTS_FAILURE";
