const MYPAGE = {
  LOAD_MYCONTENTS_REQUEST: "LOAD_MYCONTENTS_REQUEST",
  LOAD_MYCONTENTS_SUCCESS: "LOAD_MYCONTENTS_SUCCESS",
  LOAD_MYCONTENTS_FAILURE: "LOAD_MYCONTENTS_FAILURE",
};

export default MYPAGE;
