/* 전체글 가져오기 액션 */
export const LOAD_POST_REQUEST = "LOAD_POST_REQUEST";
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS";
export const LOAD_POST_FAILURE = "LOAD_POST_FAILURE";

/* 글쓰기 액션 */
export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";

/* 글 가져오기 액션 */
export const READ_POST_REQUEST = "READ_POST_REQUEST";
export const READ_POST_SUCCESS = "READ_POST_SUCCESS";
export const READ_POST_FAILURE = "READ_POST_FAILURE";

/* 댓글쓰기 액션 */
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";
